// <auto-generated />
using frontend.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace frontend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("frontend.Model.ChatRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Input")
                        .HasColumnType("text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<string>("Output")
                        .HasColumnType("text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");

                    b.Property<DateTime>("UTC");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.ToTable("ChatRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
